def repeat(c, n):
    s = ''
    i = 0
    while i < n:
        s += c
        i += 1
    return s

def line1():
    out = ''
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 9)
    out += repeat('-', 4)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 5)
    out += repeat('-', 4)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 14)
    out += repeat(':', 3)
    out += repeat('-', 14)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 13)
    out += repeat(':', 1)
    out += repeat('-', 3)
    return out

def line2():
    out = ''
    out += repeat(':', 9)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('-', 6)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 4)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 3)
    out += repeat('-', 7)
    out += repeat(':', 2)
    out += repeat('-', 14)
    out += repeat(':', 2)
    out += repeat('-', 15)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 12)
    out += repeat(':', 2)
    out += repeat('-', 3)
    return out

def line3():
    out = ''
    out += repeat(':', 4)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 9)
    out += repeat(':', 4)
    out += repeat('-', 3)
    out += repeat(':', 3)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 6)
    out += repeat(':', 3)
    out += repeat('-', 14)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 11)
    out += repeat(':', 1)
    out += repeat('-', 17)
    out += repeat(':', 1)
    out += repeat('-', 3)
    return out

def line4():
    out = ''
    out += repeat(':', 4)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 8)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 3)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat('=', 8)
    out += repeat('-', 2)
    out += repeat('=', 1)
    out += repeat('-', 3)
    out += repeat(':', 2)
    out += repeat('-', 13)
    out += repeat(':', 2)
    out += repeat('-', 17)
    out += repeat(':', 1)
    out += repeat('-', 3)
    return out

def line5():
    out = ''
    out += repeat(':', 8)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 2)
    out += repeat('-', 4)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 3)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat('=', 2)
    out += repeat('-', 1)
    out += repeat('*', 1)
    out += repeat('#', 3)
    out += repeat('*', 9)
    out += repeat('+', 1)
    out += repeat('=', 2)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 9)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 22)
    return out

def line6():
    out = ''
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('.', 3)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 6)
    out += repeat(':', 3)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 3)
    out += repeat(':', 3)
    out += repeat('-', 6)
    out += repeat('=', 1)
    out += repeat('*', 1)
    out += repeat('#', 3)
    out += repeat('%', 2)
    out += repeat('#', 4)
    out += repeat('%', 1)
    out += repeat('#', 3)
    out += repeat('%', 3)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 7)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 6)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('-', 10)
    return out

def line7():
    out = ''
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('.', 3)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 5)
    out += repeat(':', 3)
    out += repeat('-', 4)
    out += repeat(':', 4)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 3)
    out += repeat('+', 3)
    out += repeat('*', 1)
    out += repeat('%', 6)
    out += repeat('@', 5)
    out += repeat('%', 7)
    out += repeat('#', 5)
    out += repeat('+', 2)
    out += repeat('=', 2)
    out += repeat('-', 9)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 2)
    out += repeat('-', 12)
    return out

def line8():
    out = ''
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('-', 5)
    out += repeat(':', 8)
    out += repeat('-', 3)
    out += repeat(':', 4)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('*', 1)
    out += repeat('%', 3)
    out += repeat('@', 8)
    out += repeat('%', 1)
    out += repeat('@', 2)
    out += repeat('%', 3)
    out += repeat('#', 1)
    out += repeat('%', 8)
    out += repeat('#', 3)
    out += repeat('+', 2)
    out += repeat('=', 1)
    out += repeat('-', 8)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 13)
    out += repeat(':', 1)
    out += repeat('-', 5)
    return out

def line9():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 2)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 5)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('-', 4)
    out += repeat(':', 4)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat('*', 1)
    out += repeat('%', 10)
    out += repeat('#', 3)
    out += repeat('%', 2)
    out += repeat('#', 2)
    out += repeat('*', 1)
    out += repeat('#', 2)
    out += repeat('%', 10)
    out += repeat('*', 2)
    out += repeat('+', 1)
    out += repeat('-', 10)
    out += repeat(':', 1)
    out += repeat('-', 13)
    out += repeat(':', 1)
    out += repeat('-', 4)
    out += repeat(':', 1)
    out += repeat('-', 1)
    return out

def line10():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 6)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('-', 3)
    out += repeat(':', 5)
    out += repeat('-', 1)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('@', 1)
    out += repeat('%', 1)
    out += repeat('@', 1)
    out += repeat('%', 3)
    out += repeat('#', 3)
    out += repeat('*', 3)
    out += repeat('+', 7)
    out += repeat('*', 1)
    out += repeat('#', 5)
    out += repeat('%', 2)
    out += repeat('@', 3)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 6)
    out += repeat(':', 1)
    out += repeat('-', 9)
    out += repeat(':', 1)
    out += repeat('-', 7)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat('=', 1)
    return out

def line11():
    out = ''
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 8)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 11)
    out += repeat('=', 1)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('@', 2)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('+', 3)
    out += repeat('=', 3)
    out += repeat('-', 6)
    out += repeat('=', 2)
    out += repeat('-', 2)
    out += repeat('=', 1)
    out += repeat('+', 3)
    out += repeat('*', 1)
    out += repeat('#', 3)
    out += repeat('%', 5)
    out += repeat('*', 1)
    out += repeat('=', 1)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 7)
    out += repeat(':', 2)
    out += repeat('=', 1)
    out += repeat('-', 1)
    return out

def line12():
    out = ''
    out += repeat(':', 2)
    out += repeat('.', 2)
    out += repeat(':', 2)
    out += repeat('.', 2)
    out += repeat('-', 12)
    out += repeat(':', 8)
    out += repeat('-', 3)
    out += repeat('+', 1)
    out += repeat('%', 5)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 2)
    out += repeat('-', 6)
    out += repeat(':', 9)
    out += repeat('-', 6)
    out += repeat('=', 1)
    out += repeat('+', 2)
    out += repeat('*', 1)
    out += repeat('%', 1)
    out += repeat('@', 2)
    out += repeat('%', 1)
    out += repeat('=', 1)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('-', 3)
    out += repeat(':', 4)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 3)
    out += repeat('-', 3)
    return out

def line13():
    out = ''
    out += repeat(':', 2)
    out += repeat('.', 2)
    out += repeat(':', 4)
    out += repeat('-', 6)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat('*', 1)
    out += repeat('%', 1)
    out += repeat('@', 1)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('=', 3)
    out += repeat('-', 3)
    out += repeat(':', 20)
    out += repeat('-', 1)
    out += repeat('*', 1)
    out += repeat('%', 1)
    out += repeat('@', 1)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('=', 1)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 3)
    out += repeat('-', 18)
    return out

def line14():
    out = ''
    out += repeat(':', 2)
    out += repeat('.', 2)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat('-', 5)
    out += repeat(':', 3)
    out += repeat('-', 4)
    out += repeat(':', 7)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('+', 1)
    out += repeat('%', 1)
    out += repeat('@', 2)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 3)
    out += repeat('=', 3)
    out += repeat('-', 3)
    out += repeat(':', 21)
    out += repeat('-', 1)
    out += repeat('+', 1)
    out += repeat('%', 1)
    out += repeat('@', 1)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('+', 1)
    out += repeat('-', 4)
    out += repeat(':', 5)
    out += repeat('-', 6)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 5)
    return out

def line15():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 4)
    out += repeat(':', 6)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 3)
    out += repeat(':', 6)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('#', 1)
    out += repeat('@', 3)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 3)
    out += repeat('=', 3)
    out += repeat('-', 3)
    out += repeat(':', 22)
    out += repeat('-', 1)
    out += repeat('*', 1)
    out += repeat('%', 3)
    out += repeat('+', 1)
    out += repeat('-', 5)
    out += repeat(':', 3)
    out += repeat('-', 6)
    out += repeat(':', 1)
    out += repeat('-', 9)
    out += repeat(':', 1)
    out += repeat('-', 2)
    return out

def line16():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 3)
    out += repeat(':', 5)
    out += repeat('.', 2)
    out += repeat('-', 2)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 6)
    out += repeat('.', 2)
    out += repeat('-', 1)
    out += repeat('%', 1)
    out += repeat('@', 2)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 4)
    out += repeat('=', 2)
    out += repeat('-', 4)
    out += repeat(':', 22)
    out += repeat('+', 1)
    out += repeat('#', 1)
    out += repeat('%', 2)
    out += repeat('*', 1)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 2)
    out += repeat('-', 6)
    return out

def line17():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 7)
    out += repeat('.', 1)
    out += repeat(':', 6)
    out += repeat('.', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('*', 1)
    out += repeat('@', 3)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 3)
    out += repeat('=', 2)
    out += repeat('-', 5)
    out += repeat(':', 22)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('*', 1)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 7)
    return out

def line18():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 3)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('#', 1)
    out += repeat('@', 3)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 8)
    out += repeat('=', 2)
    out += repeat('-', 5)
    out += repeat(':', 6)
    out += repeat('-', 2)
    out += repeat(':', 8)
    out += repeat('-', 1)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('*', 1)
    out += repeat('-', 5)
    out += repeat(':', 3)
    out += repeat('-', 10)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 5)
    return out

def line19():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 2)
    out += repeat('-', 2)
    out += repeat('.', 4)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('.', 3)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat('#', 1)
    out += repeat('@', 2)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('%', 9)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 2)
    out += repeat('-', 5)
    out += repeat('=', 5)
    out += repeat('-', 2)
    out += repeat(':', 4)
    out += repeat('-', 1)
    out += repeat('+', 1)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('-', 5)
    out += repeat(':', 2)
    out += repeat('-', 14)
    out += repeat(':', 1)
    out += repeat('-', 5)
    return out

def line20():
    out = ''
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 3)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('#', 1)
    out += repeat('%', 3)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('*', 5)
    out += repeat('#', 1)
    out += repeat('%', 3)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('=', 3)
    out += repeat('+', 1)
    out += repeat('*', 2)
    out += repeat('#', 2)
    out += repeat('%', 4)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 2)
    out += repeat('+', 1)
    out += repeat('#', 3)
    out += repeat('+', 1)
    out += repeat('-', 6)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 9)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 2)
    return out

def line21():
    out = ''
    out += repeat('.', 3)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 2)
    out += repeat(':', 4)
    out += repeat('.', 2)
    out += repeat(':', 4)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('=', 1)
    out += repeat('%', 3)
    out += repeat('#', 1)
    out += repeat('+', 2)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('#', 4)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('#', 5)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('*', 1)
    out += repeat('%', 5)
    out += repeat('#', 4)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('+', 1)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('#', 3)
    out += repeat('=', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 11)
    out += repeat(':', 2)
    out += repeat('-', 3)
    return out

def line22():
    out = ''
    out += repeat('.', 2)
    out += repeat(':', 2)
    out += repeat('.', 3)
    out += repeat(':', 7)
    out += repeat('.', 3)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 3)
    out += repeat(':', 2)
    out += repeat('=', 1)
    out += repeat('#', 3)
    out += repeat('%', 3)
    out += repeat('+', 4)
    out += repeat('*', 1)
    out += repeat('%', 4)
    out += repeat('#', 1)
    out += repeat('@', 2)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('=', 1)
    out += repeat('-', 3)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('#', 5)
    out += repeat('*', 3)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('-', 2)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('-', 6)
    out += repeat(':', 2)
    out += repeat('-', 6)
    out += repeat(':', 1)
    out += repeat('-', 6)
    out += repeat(':', 3)
    out += repeat('-', 4)
    return out

def line23():
    out = ''
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat('=', 1)
    out += repeat('#', 1)
    out += repeat('%', 4)
    out += repeat('#', 1)
    out += repeat('+', 2)
    out += repeat('=', 4)
    out += repeat('+', 1)
    out += repeat('*', 5)
    out += repeat('+', 2)
    out += repeat('=', 5)
    out += repeat(':', 3)
    out += repeat('=', 2)
    out += repeat('+', 4)
    out += repeat('%', 1)
    out += repeat('@', 1)
    out += repeat('#', 4)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 2)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('+', 1)
    out += repeat('-', 4)
    out += repeat(':', 5)
    out += repeat('-', 12)
    out += repeat(':', 3)
    out += repeat('-', 4)
    return out

def line24():
    out = ''
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 5)
    out += repeat('.', 5)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 5)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat('-', 1)
    out += repeat('+', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('+', 1)
    out += repeat('=', 3)
    out += repeat('-', 2)
    out += repeat('=', 5)
    out += repeat('-', 4)
    out += repeat('=', 2)
    out += repeat('-', 1)
    out += repeat(':', 4)
    out += repeat('-', 1)
    out += repeat('=', 2)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('#', 2)
    out += repeat('*', 2)
    out += repeat('=', 3)
    out += repeat('-', 3)
    out += repeat('+', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('-', 2)
    out += repeat(':', 6)
    out += repeat('-', 13)
    out += repeat(':', 2)
    out += repeat('-', 5)
    return out

def line25():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 4)
    out += repeat('.', 3)
    out += repeat(':', 3)
    out += repeat('.', 2)
    out += repeat(':', 5)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('+', 2)
    out += repeat('#', 2)
    out += repeat('*', 2)
    out += repeat('+', 2)
    out += repeat('=', 3)
    out += repeat('-', 7)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat('=', 2)
    out += repeat('-', 1)
    out += repeat(':', 7)
    out += repeat('-', 2)
    out += repeat('=', 5)
    out += repeat('-', 4)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('*', 1)
    out += repeat('=', 1)
    out += repeat('%', 1)
    out += repeat('*', 1)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 6)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 6)
    out += repeat(':', 3)
    out += repeat('-', 5)
    return out

def line26():
    out = ''
    out += repeat('.', 2)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 3)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 5)
    out += repeat('=', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('*', 1)
    out += repeat('#', 2)
    out += repeat('*', 2)
    out += repeat('+', 1)
    out += repeat('=', 4)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat('=', 3)
    out += repeat('-', 1)
    out += repeat(':', 5)
    out += repeat('-', 1)
    out += repeat(':', 12)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('+', 1)
    out += repeat('-', 1)
    out += repeat('#', 1)
    out += repeat('=', 1)
    out += repeat('-', 1)
    out += repeat(':', 5)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 6)
    out += repeat(':', 3)
    out += repeat('-', 5)
    return out

def line27():
    out = ''
    out += repeat('.', 1)
    out += repeat(':', 6)
    out += repeat('.', 3)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 5)
    out += repeat('-', 4)
    out += repeat('=', 2)
    out += repeat('+', 1)
    out += repeat('*', 4)
    out += repeat('+', 2)
    out += repeat('=', 4)
    out += repeat('-', 4)
    out += repeat('=', 2)
    out += repeat('#', 1)
    out += repeat('@', 2)
    out += repeat('%', 1)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('*', 2)
    out += repeat('=', 1)
    out += repeat('-', 3)
    out += repeat(':', 9)
    out += repeat('-', 2)
    out += repeat('=', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('+', 1)
    out += repeat('-', 1)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 4)
    out += repeat(':', 4)
    out += repeat('-', 6)
    return out

def line28():
    out = ''
    out += repeat('.', 2)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 5)
    out += repeat('.', 2)
    out += repeat(':', 7)
    out += repeat('-', 3)
    out += repeat('*', 6)
    out += repeat('+', 4)
    out += repeat('=', 8)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('@', 3)
    out += repeat('%', 2)
    out += repeat('@', 2)
    out += repeat('%', 1)
    out += repeat('*', 1)
    out += repeat('=', 1)
    out += repeat('-', 6)
    out += repeat(':', 3)
    out += repeat('-', 3)
    out += repeat('=', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 1)
    out += repeat(':', 7)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 5)
    out += repeat(':', 3)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 3)
    return out

def line29():
    out = ''
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 2)
    out += repeat(':', 4)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat('*', 1)
    out += repeat('%', 1)
    out += repeat('*', 5)
    out += repeat('+', 7)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('*', 1)
    out += repeat('#', 3)
    out += repeat('%', 2)
    out += repeat('@', 1)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('=', 4)
    out += repeat('-', 9)
    out += repeat('=', 2)
    out += repeat('-', 2)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 3)
    out += repeat('-', 4)
    out += repeat(':', 1)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 3)
    return out

def line30():
    out = ''
    out += repeat('-', 1)
    out += repeat(':', 5)
    out += repeat('.', 3)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('-', 3)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('*', 5)
    out += repeat('+', 5)
    out += repeat('*', 1)
    out += repeat('#', 2)
    out += repeat('%', 2)
    out += repeat('#', 3)
    out += repeat('*', 2)
    out += repeat('#', 2)
    out += repeat('*', 1)
    out += repeat('#', 4)
    out += repeat('*', 2)
    out += repeat('+', 2)
    out += repeat('=', 3)
    out += repeat('-', 6)
    out += repeat('=', 2)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 4)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 7)
    return out

def line31():
    out = ''
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('*', 3)
    out += repeat('+', 4)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('@', 3)
    out += repeat('%', 9)
    out += repeat('#', 4)
    out += repeat('%', 1)
    out += repeat('#', 2)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('=', 7)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 15)
    out += repeat(':', 2)
    out += repeat('-', 7)
    return out

def line32():
    out = ''
    out += repeat(':', 2)
    out += repeat('.', 2)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 3)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat('+', 1)
    out += repeat('#', 4)
    out += repeat('*', 2)
    out += repeat('+', 3)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('#', 4)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 2)
    out += repeat('=', 2)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('%', 1)
    out += repeat('@', 4)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('+', 2)
    out += repeat('=', 6)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 2)
    out += repeat('-', 6)
    out += repeat(':', 2)
    out += repeat('-', 7)
    return out

def line33():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 2)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 4)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 3)
    out += repeat(':', 2)
    out += repeat('+', 1)
    out += repeat('#', 1)
    out += repeat('%', 2)
    out += repeat('#', 3)
    out += repeat('*', 3)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('*', 1)
    out += repeat('#', 6)
    out += repeat('*', 3)
    out += repeat('+', 2)
    out += repeat('#', 1)
    out += repeat('%', 4)
    out += repeat('+', 9)
    out += repeat('-', 7)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat('-', 6)
    out += repeat(':', 2)
    out += repeat('-', 8)
    return out

def line34():
    out = ''
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 5)
    out += repeat('.', 4)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat('=', 1)
    out += repeat('#', 2)
    out += repeat('%', 5)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('+', 4)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 2)
    out += repeat('@', 4)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('+', 2)
    out += repeat('*', 5)
    out += repeat('+', 5)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('-', 5)
    out += repeat(':', 3)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 3)
    out += repeat('-', 5)
    out += repeat(':', 2)
    out += repeat('-', 8)
    return out

def line35():
    out = ''
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 3)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat(':', 2)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('+', 1)
    out += repeat('%', 3)
    out += repeat('@', 3)
    out += repeat('%', 1)
    out += repeat('#', 2)
    out += repeat('*', 1)
    out += repeat('+', 5)
    out += repeat('=', 2)
    out += repeat('+', 1)
    out += repeat('*', 2)
    out += repeat('+', 6)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('#', 2)
    out += repeat('*', 3)
    out += repeat('=', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 6)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 4)
    out += repeat('-', 5)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 6)
    return out

def line36():
    out = ''
    out += repeat(':', 4)
    out += repeat('.', 3)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 3)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('+', 1)
    out += repeat('%', 1)
    out += repeat('@', 7)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('+', 5)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 4)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 4)
    out += repeat('#', 1)
    out += repeat('+', 1)
    out += repeat(':', 3)
    out += repeat('-', 6)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 4)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 5)
    return out

def line37():
    out = ''
    out += repeat(':', 3)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 2)
    out += repeat(':', 4)
    out += repeat('.', 5)
    out += repeat('-', 3)
    out += repeat(':', 2)
    out += repeat('-', 5)
    out += repeat(':', 2)
    out += repeat('*', 1)
    out += repeat('%', 2)
    out += repeat('@', 9)
    out += repeat('%', 2)
    out += repeat('#', 4)
    out += repeat('%', 4)
    out += repeat('#', 2)
    out += repeat('*', 4)
    out += repeat('%', 1)
    out += repeat('@', 3)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('+', 2)
    out += repeat('=', 2)
    out += repeat('-', 5)
    out += repeat(':', 4)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 3)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 1)
    return out

def line38():
    out = ''
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 2)
    out += repeat('.', 4)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat('+', 1)
    out += repeat('%', 1)
    out += repeat('@', 2)
    out += repeat('%', 2)
    out += repeat('@', 22)
    out += repeat('%', 6)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('@', 4)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('=', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 5)
    out += repeat(':', 2)
    out += repeat('-', 4)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 2)
    out += repeat('-', 4)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    return out

def line39():
    out = ''
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 4)
    out += repeat('.', 1)
    out += repeat(':', 3)
    out += repeat('.', 6)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat('#', 1)
    out += repeat('@', 29)
    out += repeat('%', 4)
    out += repeat('#', 2)
    out += repeat('*', 2)
    out += repeat('+', 2)
    out += repeat('%', 1)
    out += repeat('@', 4)
    out += repeat('%', 3)
    out += repeat('#', 2)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 3)
    out += repeat(':', 2)
    out += repeat('-', 3)
    out += repeat(':', 2)
    out += repeat('-', 2)
    out += repeat(':', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    return out

def line40():
    out = ''
    out += repeat(':', 2)
    out += repeat('.', 2)
    out += repeat(':', 3)
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 4)
    out += repeat('.', 3)
    out += repeat(':', 1)
    out += repeat('.', 1)
    out += repeat(':', 1)
    out += repeat('=', 1)
    out += repeat('#', 1)
    out += repeat('%', 3)
    out += repeat('@', 2)
    out += repeat('%', 1)
    out += repeat('@', 27)
    out += repeat('%', 2)
    out += repeat('#', 2)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('#', 1)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('%', 9)
    out += repeat('#', 2)
    out += repeat('*', 7)
    out += repeat('+', 3)
    out += repeat('=', 1)
    out += repeat(':', 4)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('.', 1)
    return out

def line41():
    out = ''
    out += repeat('.', 2)
    out += repeat(':', 1)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('.', 4)
    out += repeat(':', 1)
    out += repeat('=', 1)
    out += repeat('+', 1)
    out += repeat('#', 2)
    out += repeat('%', 11)
    out += repeat('@', 2)
    out += repeat('%', 1)
    out += repeat('@', 27)
    out += repeat('%', 1)
    out += repeat('#', 2)
    out += repeat('*', 3)
    out += repeat('+', 1)
    out += repeat('*', 1)
    out += repeat('@', 2)
    out += repeat('%', 1)
    out += repeat('@', 1)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('%', 12)
    out += repeat('#', 3)
    out += repeat('%', 4)
    out += repeat('#', 2)
    out += repeat('*', 1)
    out += repeat('=', 2)
    out += repeat('-', 1)
    out += repeat(':', 1)
    out += repeat('-', 3)
    out += repeat(':', 1)
    out += repeat('.', 1)
    return out

def line42():
    out = ''
    out += repeat(':', 1)
    out += repeat('-', 2)
    out += repeat(':', 1)
    out += repeat('.', 2)
    out += repeat('=', 1)
    out += repeat('*', 1)
    out += repeat('%', 2)
    out += repeat('#', 2)
    out += repeat('%', 13)
    out += repeat('@', 1)
    out += repeat('%', 3)
    out += repeat('@', 25)
    out += repeat('%', 2)
    out += repeat('#', 2)
    out += repeat('*', 3)
    out += repeat('#', 1)
    out += repeat('@', 3)
    out += repeat('%', 2)
    out += repeat('@', 1)
    out += repeat('%', 2)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('%', 10)
    out += repeat('#', 5)
    out += repeat('%', 2)
    out += repeat('#', 6)
    out += repeat('*', 1)
    out += repeat('+', 1)
    out += repeat('=', 1)
    out += repeat('-', 1)
    return out

def line43():
    out = ''
    out += repeat('-', 1)
    out += repeat('+', 1)
    out += repeat('#', 1)
    out += repeat('%', 9)
    out += repeat('#', 1)
    out += repeat('%', 13)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('@', 8)
    out += repeat('%', 1)
    out += repeat('@', 16)
    out += repeat('%', 3)
    out += repeat('#', 4)
    out += repeat('%', 1)
    out += repeat('@', 5)
    out += repeat('%', 6)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('%', 8)
    out += repeat('#', 2)
    out += repeat('%', 2)
    out += repeat('#', 9)
    out += repeat('*', 1)
    out += repeat('#', 2)
    return out

def line44():
    out = ''
    out += repeat('%', 3)
    out += repeat('#', 1)
    out += repeat('%', 8)
    out += repeat('#', 2)
    out += repeat('%', 11)
    out += repeat('#', 2)
    out += repeat('%', 2)
    out += repeat('@', 8)
    out += repeat('%', 2)
    out += repeat('@', 16)
    out += repeat('%', 2)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('@', 1)
    out += repeat('%', 1)
    out += repeat('@', 3)
    out += repeat('%', 8)
    out += repeat('#', 1)
    out += repeat('*', 2)
    out += repeat('+', 1)
    out += repeat('#', 1)
    out += repeat('%', 5)
    out += repeat('#', 2)
    out += repeat('%', 6)
    out += repeat('#', 6)
    out += repeat('*', 1)
    out += repeat('#', 1)
    return out

def line45():
    out = ''
    out += repeat('%', 4)
    out += repeat('#', 2)
    out += repeat('%', 7)
    out += repeat('#', 1)
    out += repeat('%', 10)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 2)
    out += repeat('@', 9)
    out += repeat('%', 3)
    out += repeat('@', 10)
    out += repeat('%', 1)
    out += repeat('#', 3)
    out += repeat('*', 2)
    out += repeat('#', 1)
    out += repeat('%', 4)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('@', 3)
    out += repeat('%', 9)
    out += repeat('#', 3)
    out += repeat('%', 3)
    out += repeat('#', 1)
    out += repeat('%', 1)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('%', 7)
    out += repeat('#', 1)
    out += repeat('*', 1)
    out += repeat('#', 5)
    return out

def line46():
    out = ''
    out += repeat('%', 5)
    out += repeat('#', 2)
    out += repeat('%', 6)
    out += repeat('#', 2)
    out += repeat('%', 9)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 6)
    out += repeat('@', 8)
    out += repeat('%', 5)
    out += repeat('@', 4)
    out += repeat('%', 3)
    out += repeat('#', 4)
    out += repeat('%', 4)
    out += repeat('#', 1)
    out += repeat('*', 3)
    out += repeat('@', 2)
    out += repeat('%', 9)
    out += repeat('#', 2)
    out += repeat('%', 7)
    out += repeat('#', 3)
    out += repeat('%', 7)
    out += repeat('#', 6)
    return out

def line47():
    out = ''
    out += repeat('%', 7)
    out += repeat('@', 4)
    out += repeat('%', 3)
    out += repeat('#', 1)
    out += repeat('%', 8)
    out += repeat('*', 1)
    out += repeat('#', 1)
    out += repeat('%', 7)
    out += repeat('@', 1)
    out += repeat('%', 3)
    out += repeat('@', 2)
    out += repeat('%', 2)
    out += repeat('@', 1)
    out += repeat('%', 16)
    out += repeat('#', 2)
    out += repeat('*', 1)
    out += repeat('+', 2)
    out += repeat('=', 1)
    out += repeat('+', 1)
    out += repeat('@', 2)
    out += repeat('%', 3)
    out += repeat('#', 4)
    out += repeat('%', 1)
    out += repeat('#', 2)
    out += repeat('%', 7)
    out += repeat('#', 5)
    out += repeat('%', 7)
    out += repeat('#', 6)
    return out

def line48():
    out = ''
    return out

functions = [
    line1,
    line2,
    line3,
    line4,
    line5,
    line6,
    line7,
    line8,
    line9,
    line10,
    line11,
    line12,
    line13,
    line14,
    line15,
    line16,
    line17,
    line18,
    line19,
    line20,
    line21,
    line22,
    line23,
    line24,
    line25,
    line26,
    line27,
    line28,
    line29,
    line30,
    line31,
    line32,
    line33,
    line34,
    line35,
    line36,
    line37,
    line38,
    line39,
    line40,
    line41,
    line42,
    line43,
    line44,
    line45,
    line46,
    line47,
    line48,
]

for f in functions:
    print(f())
